<?xml version="1.0" encoding="utf-8"?><Database Name="AllPlayers" Class="ChangeTrainerLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\ajari\OneDrive\Documenten\AllPlayers.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="PlayersGenerator2.Properties.Settings" SettingsPropertyName="AllPlayersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CurrentTrainer" Member="CurrentTrainerAnds">
    <Type Name="CurrentTrainerAnd">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="exclub" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>